version: "3.9"

services:
  webserver:
    build:
      args:
        BUILD_ENV: 'prod'
  celery:
    build:
      args:
        BUILD_ENV: 'prod'
    volumes:
      - explori-cache:/explori/celery/cache
      - explori-uploaded:/explori/celery/data/uploaded
  fastapi:
    build:
      args:
        BUILD_ENV: 'prod'
    volumes:
      - explori-cache:/explori/fastapi/cache
      - explori-uploaded:/explori/fastapi/data/uploaded

volumes:
  explori-cache:
  explori-uploaded:
