version: "3.9"

services:
  webserver:
    build:
      args:
        BUILD_ENV: 'prod'
  celery:
    build:
      args:
        BUILD_ENV: 'prod'
    volumes:
      - cache:/explori/celery/cache
      - data:/explori/celery/data
  fastapi:
    build:
      args:
        BUILD_ENV: 'prod'
    volumes:
      - cache:/explori/fastapi/cache
      - data:/explori/fastapi/data

volumes:
  cache:
  data: