FROM --platform=linux/amd64 python:3.10-slim@sha256:e04bc5390a13e6e910980715f1156552fbd3deddf7668e1892575989f9504c70 AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_ROOT_USER_ACTION=ignore
COPY requirements.txt .
RUN pip install -r requirements.txt

FROM python:3.10-slim@sha256:e04bc5390a13e6e910980715f1156552fbd3deddf7668e1892575989f9504c70
# libgomp1 needed for pm4py parallelism
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
