FROM python:3.10

ENV DEV=1
ENV EXPLORI_REDIS_HOST=redis
ENV EXPLORI_REDIS_PORT=6379

WORKDIR /explori/fastapi

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY src/ src/
COPY data/ data/

CMD PYTHONUNBUFFERED=1 DEV=${DEV} EXPLORI_REDIS_HOST=${EXPLORI_REDIS_HOST} EXPLORI_REDIS_PORT=${EXPLORI_REDIS_PORT} PYTHONPATH="src/" uvicorn server.main:app --host 0.0.0.0 --port 8080
