FROM python:3.10

# PYTHONPATH: needed to specify the celery app `worker.main.app` relative to it
# EXPLORI_REDIS_HOST: needed to specify the address of the redis docker container (simply its name since they're in the same docker network)
ENV EXPLORI_REDIS_HOST=redis
ENV EXPLORI_REDIS_PORT=6379

WORKDIR /explori/celery

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/ src/
COPY data/ data/

CMD PYTHONUNBUFFERED=1 EXPLORI_REDIS_HOST=${EXPLORI_REDIS_HOST} EXPLORI_REDIS_PORT=${EXPLORI_REDIS_PORT} PYTHONPATH="src/" celery --app=worker.main.app worker --loglevel=INFO
